<a href="https://colab.research.google.com/github/moizarsalan/Programming-for-AI-lab/blob/Programming-for-AI-Lab-Tasks/Lab_12_NumPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 12**

**Working with NumPY**

**Lab Task 01**

**Creating NumPY Arrays**

In [1]:
import numpy as np
my_list = [0,1,2,3,4,5,6,7,8,9,10]
nparr = np.array(my_list)
print(nparr)

[ 0  1  2  3  4  5  6  7  8  9 10]


**Lab Task 02**

**Form Built-in Method**

In [2]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


**Lab Task 03**

**Universal Functions**

We can perform arithmatic operations using universal functions.



1.   Addition
2.   Subtraction
1.   Multiplication
2.   Division

In [6]:
#Adding Arrays
nparr_added = nparr + nparr
print("\nAddition")
print(nparr_added)

#Subtracting Arrays
nparr_sub= nparr - nparr
print("\nSubtraction")
print(nparr_sub)

#Multiplying Arrays
nparr_mul= nparr * nparr
print("\nMultiplication")
print(nparr_mul)

#Dividing Arrays
nparr_div= nparr / nparr
print("\nDivision")
print(nparr_div)


Addition
[ 0  2  4  6  8 10 12 14 16 18 20]

Subtraction
[0 0 0 0 0 0 0 0 0 0 0]

Multiplication
[  0   1   4   9  16  25  36  49  64  81 100]

Division
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-6-b8d6258c5ed6>:17: RuntimeWarning: invalid value encountered in divide
  nparr_div= nparr / nparr


**Following Operations can also be performed**



1.   Multiply by Scalers
2.   One divided by zero
1.   EXPONENT — ARRAYS — Squaring everything — Two options
2.   Square Root
1.   Exponential with arrays
2.   Max & Min
1.   TRIGONOMETRIC FUNCTIONS — Passing every element into sine function
2.   LOGARITHMIC — Note: the very first one is minus infinity












## **1. Multiplying By Scalers**

In [7]:
nparr_esc = nparr * 10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


# **2. One Divided by Zero**

In [8]:
# inf signifies infinity for one divided
# by zero at the very first element
nparr_one_div = 1/nparr
print(nparr_one_div)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-8-ba66c1bd8c7d>:3: RuntimeWarning: divide by zero encountered in divide
  nparr_one_div = 1/nparr


# **3.   EXPONENT — ARRAYS — Squaring everything — Two options**

In [ ]:
np_arr_exp1 = nparr ** 2
print(np_arr_exp1)
np_arr_exp2 = np.square(nparr)
print(np_arr_exp2)

# **4. Square Root**

In [9]:
nparr_sr = np.sqrt(nparr)
print(nparr_sr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


# **5. Exponential with arrays**

In [10]:
np_arr_exp3 = np.exp(nparr)
print(np_arr_exp3)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


# **6. Max & Min**

In [11]:
#Max
nparr_max = np.max(arr)
print(nparr_max)

#Min
nparr_min = np.min(arr)
print(nparr_min)

10
0


# **7. TRIGONOMETRIC FUNCTIONS — Passing every element into sine function**

In [12]:
nparr_sin = np.sin(nparr)
print(nparr_sin)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


# **8. LOGARITHMIC — Note: the very first one is minus infinity**

In [13]:
nparr_log = np.log(nparr)
print(nparr_log)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


<ipython-input-13-e7c9468d2519>:1: RuntimeWarning: divide by zero encountered in log
  nparr_log = np.log(nparr)
